# Generated by Django 3.2.5 on 2021-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
